#!/bin/sh

make distclean

echo cleaning root
rm -rf aclocal.m4 \
       autom4te.cache \
       autoscan.log \
       config.guess \
       config.h.in~ \
       config.log \
       config.status \
       config.sub \
       configure \
       configure.scan \
       depcomp \
       install-sh \
       libtool \
       ltmain.sh \
       missing \
       `find . -name Makefile.in`

pwd

echo cleaning m4
cd m4 && rm -rf \
       libtool.m4 \
       lt~obsolete.m4 \
       ltoptions.m4 \
       ltsugar.m4 \
       ltversion.m4
cd ..
