#!/bin/sh

make distclean

rm -rf aclocal.m4 \
       autom4te.cache \
       Makefile \
       Makefile.in \
       autoscan.log \
       config.* \
       configure \
       compile \
       configure.scan \
       depcomp \
       install-sh \
       libtool \
       ltmain.sh \
       missing


